import os
import datetime
import subprocess
from huggingface_hub import InferenceClient

# Initialize Hugging Face client
client = InferenceClient(
    provider="hf-inference",
    api_key=os.getenv("HF")
)

# Step 1: Generate sample code using Hugging Face chat model
def generate_sample_code():
    print("Generating code...")
    messages = [
        {
            "role": "user",
            "content": "Generate a simple Python function that checks if a number is a palindrome."
        }
    ]

    stream = client.chat.completions.create(
        model="google/gemma-2-2b-it", 
        messages=messages, 
        max_tokens=500,
        stream=True
    )

    # Collect all streamed chunks
    generated_code = ""
    for chunk in stream:
        if chunk.choices and chunk.choices[0].delta and chunk.choices[0].delta.content:
            generated_code += chunk.choices[0].delta.content
    return generated_code

# Step 2: Save the generated code into a new file
def save_code_to_file(code):
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"sample_code_{timestamp}.py"
    with open(filename, "w") as f:
        f.write("# Auto-generated by Gemma\n\n")
        f.write(code)
    return filename

# Step 3: Git add, commit, and push
def git_commit_and_push(filename):
    try:
        subprocess.run(["git", "config", "--global", "user.name", "vinishdas"], check=True)
        subprocess.run(["git", "config", "--global", "user.email", "dvinish6669@gmail.com"], check=True)

        subprocess.run(["git", "add", filename], check=True)
        subprocess.run(["git", "commit", "-m", f"🤖 Auto-commit: add {filename}"], check=True)
        subprocess.run(["git", "push"], check=True)

        print(f"✅ Successfully committed and pushed {filename}")
    except subprocess.CalledProcessError as e:
        print(f"❌ Git command failed: {e}")

# Main runner
def main():
    code = generate_sample_code()
    filename = save_code_to_file(code)
    git_commit_and_push(filename)

if __name__ == "__main__":
    main()
