import os
import random
import datetime
import subprocess
from openai import OpenAI

# Initialize OpenAI client
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# Step 1: Generate sample code using GPT
def generate_sample_code():
    print("Generating code...")
    completion = client.chat.completions.create(
        model="gpt-3.5-turbo",  # or "gpt-4o" if your key supports it
        messages=[
            {
                "role": "system",
                "content": "You are a helpful assistant that writes short Python code samples for learning."
            },
            {
                "role": "user",
                "content": "Generate a simple Python function that checks if a number is a palindrome."
            }
        ]
    )
    return completion.choices[0].message.content

# Step 2: Save the generated code into a new file
def save_code_to_file(code):
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"sample_code_{timestamp}.py"
    with open(filename, "w") as f:
        f.write("# Auto-generated by GPT\n\n")
        f.write(code)
    return filename

# Step 3: Git add, commit, and push
def git_commit_and_push(filename):
    try:
        subprocess.run(["git", "config", "--global", "user.name", "your-github-username"], check=True)
        subprocess.run(["git", "config", "--global", "user.email", "your-email@example.com"], check=True)

        subprocess.run(["git", "add", filename], check=True)
        subprocess.run(["git", "commit", "-m", f"🤖 Auto-commit: add {filename}"], check=True)
        subprocess.run(["git", "push"], check=True)

        print(f"✅ Successfully committed and pushed {filename}")
    except subprocess.CalledProcessError as e:
        print(f"❌ Git command failed: {e}")

# Main runner
def main():
    code = generate_sample_code()
    filename = save_code_to_file(code)
    git_commit_and_push(filename)

if __name__ == "__main__":
    main()
