# Auto-generated by Gemma

```python
def percolate(matrix, x, y):
  if x < 0 or x >= len(matrix) or y < 0 or y >= len(matrix[0]):
    return 
  matrix[x][y] = 0
  percolate(matrix, x + 1, y)
  percolate(matrix, x - 1, y)
  percolate(matrix, x, y + 1)
  percolate(matrix, x, y - 1)
```