# Auto-generated by Gemma

```python
import numpy as np

def auto_sort_groups(data):
  groups = np.unique(data, return_index=True)
  sorted_indices = np.argsort(groups[0]) 
  return sorted_indices, groups[1] 
```