# Auto-generated by Gemma

```python
import random

def random_word_sequencer(length=5):
  alphabet = 'abcdefghijklmnopqrstuvwxyz'
  return ''.join([random.choice(alphabet) for _ in range(length)])
```