# Auto-generated by Gemma

```python
from typing import List

def dragonfly_dance(grid: List[List[int]]) -> int:
  m, n = len(grid), len(grid[0])
  max_steps = 0
  
  def explore(row: int, col: int) -> int:
    if row < 0 or row >= m or col < 0 or col >= n or grid[row][col] == 0:
      return 0
    grid[row][col] = 0
    steps = explore(row + 1, col) + explore(row - 1, col) + explore(row, col + 1) + explore(row, col - 1)
    max_steps = max(max_steps, steps)
    return steps
  
  for i in range(m):
    for j in range(n):
      explore(i, j)
  return max_steps   
```