# Auto-generated by Gemma

```python
import random

def chaotic_rotate(array):
  n = len(array)
  random.shuffle(array)
  for i in range(n // 2):
    j = random.randint(i + 1, n - i - 1)
    array[i], array[j] = array[j], array[i]
  return array
```