# Auto-generated by Gemma

```python
import random

def generate_random_adjective():
  return random.choice(["awesome", "silly", "glittery", "whimsical", "bouncy", "sparkling", "sleepy", "magical", "spicy", "ancient"])
```