# Auto-generated by Gemma

```python
from typing import Tuple

def extract_keywords(text: str) -> Tuple[str, float]:
  words = text.lower().split()
  keyword_count = len(set(words))
  
  return f"Keywords: {' '.join(words)}", keyword_count / len(words) 
```