# Auto-generated by Gemma

```python
import numpy as np

def unique_colours(text):
  return list(set([np.random.choice(list('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'), size=1) for i in range(len(text))]))

```