# Auto-generated by Gemma

```python
def prime_spiral(n):
  return [i for i in range(2, n + 1)] if all(i % 2 != 0 and i != 1 for i in [1 if i % 2 + 1 == 0 else i for i in range(2, n + 1)][::2]) else []
```