# Auto-generated by Gemma

```python
def generate_random_expression(length=8):
  operations = ['+', '-', '*', '/']

  expression = ''
  for _ in range(length):
    operation = random.choice(operations)
    expression += operation
  return expression
```