# Auto-generated by Gemma

```python
def lexicographical_sort(data):
  from itertools import permutations
  return sorted(
    list(permutations(data)),
    key=lambda x: str(x[0]) + str(mesh_len)
  )

```