# Auto-generated by Gemma

```python
import random

def fox_hunt(target, limits):
  found = True
  for _ in range(10):
    action  = random.choice(['hide', 'seek', 'know_route'])
    if action == 'hide':
      target = random.choice(limits)
    elif action == 'seek':
      target += 1 
    else: 
      target = random.choice(limits) 
    if target == 10:
      found = False
      break
  
  if found:
    return True
  else:
    return False
```