# Auto-generated by Gemma

```python
import random

def generate_fibonacci_number(n):
  if n <= 1:
    return n
  else:
    return generate_fibonacci_number(n - 1) + generate_fibonacci_number(n - 2)
```