# Auto-generated by Gemma

```python
def fibonacci_matrix(n):
  matrix = [[0, 0], [0, 1]]
  for i in range(2, n):
    row = [0, 1]
    for j in range(2, i + 1):
      row[j] = matrix[i - 1][j - 1] + matrix[i - 1][j]
    matrix.append(row)
  return matrix
```